dbt_assignment:
  outputs:
    dev:
      dataset: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:\Users\RANEJA\work\bigquerykey\dbt-assignment-389607-dd58bf1c674f.json
      location: US
      method: service-account
      priority: interactive
      project: dbt-assignment-389607
      threads: 4
      type: bigquery
  target: dev
